### ISSUE TITLE
Project is not Working

### ISSUE THREAD

**Issue by Rabi8961** [saibbyweb/Realtime-Location-Tracking-NativeScript-Vue#5]
I clone your project. i install all dependency. i provide google api key.
but, when i run it no map is showing.
please look at screen shot
![Screenshot_20190924-192743](https://user-images.githubusercontent.com/31152473/65518494-0054d900-df02-11e9-9710-b873d36e6d21.png)

**Comment by saibbyweb** [comment]
Apologies for the late response. It must be something with the API keys, hope you have resolved the issue as of now. If not, I am here to help.
